name: Using reusable workflow
on: 
    workflow_dispatch:
        inputs:
            name:
                description: 'input description'
                type: string
                default: 'Vikas'
                required: false

jobs:
    calling-reusable-wf:
        uses: vikas-bhapri/reusable-workflows/.github/workflows/resuable.yaml@master
        with:
            name: ${{ inputs.name }}
        secrets:
            access_token: ${{ secrets.ACCESS_TOKEN }}

